# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emissions/v3/nonce.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'emissions/v3/nonce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmospy_protobuf.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65missions/v3/nonce.proto\x12\x0c\x65missions.v3\x1a\x14gogoproto/gogo.proto\"#\n\x05Nonce\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\x03:\x04\xe8\xa0\x1f\x01\"-\n\x06Nonces\x12#\n\x06nonces\x18\x01 \x03(\x0b\x32\x13.emissions.v3.Nonce\"G\n\x13ReputerRequestNonce\x12*\n\rreputer_nonce\x18\x01 \x01(\x0b\x32\x13.emissions.v3.Nonce:\x04\xe8\xa0\x1f\x01\"I\n\x14ReputerRequestNonces\x12\x31\n\x06nonces\x18\x01 \x03(\x0b\x32!.emissions.v3.ReputerRequestNonceB:Z8github.com/allora-network/allora-chain/x/emissions/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emissions.v3.nonce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/allora-network/allora-chain/x/emissions/types'
  _globals['_NONCE']._loaded_options = None
  _globals['_NONCE']._serialized_options = b'\350\240\037\001'
  _globals['_REPUTERREQUESTNONCE']._loaded_options = None
  _globals['_REPUTERREQUESTNONCE']._serialized_options = b'\350\240\037\001'
  _globals['_NONCE']._serialized_start=64
  _globals['_NONCE']._serialized_end=99
  _globals['_NONCES']._serialized_start=101
  _globals['_NONCES']._serialized_end=146
  _globals['_REPUTERREQUESTNONCE']._serialized_start=148
  _globals['_REPUTERREQUESTNONCE']._serialized_end=219
  _globals['_REPUTERREQUESTNONCES']._serialized_start=221
  _globals['_REPUTERREQUESTNONCES']._serialized_end=294
# @@protoc_insertion_point(module_scope)
